
# actual size of the window
SCREEN_WIDTH = 40
SCREEN_HEIGHT = 30
 
# size of the map
MAP_WIDTH = 60
MAP_HEIGHT = 50
 
# sizes and coordinates relevant for the GUI
BAR_WIDTH = 8
PANEL_HEIGHT = 7
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT
MSG_X = BAR_WIDTH + 3
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 3
MSG_HEIGHT = PANEL_HEIGHT - 1
INVENTORY_WIDTH = 50
ACTION_MENU_WIDTH = 50
CHARACTER_SCREEN_WIDTH = 30
LEVEL_SCREEN_WIDTH = 40
 
# parameters for dungeon generator
ROOM_MAX_SIZE = 10
ROOM_MIN_SIZE = 4
MAX_ROOMS = 20
 
# spell values
#HEAL_AMOUNT = 40
NO_RANGE = 1000
LIGHTNING_DAMAGE = 8
LIGHTNING_RANGE = 3
FEAR_RANGE = 5
FEAR_DURATION = 3
CONFUSE_RANGE = 8
CONFUSE_NUM_TURNS = 10
POSSESS_RANGE = 10
FIREBALL_RADIUS = 2
FIREBALL_RANGE = 7
FIREBALL_DAMAGE = 5
FREEZE_RANGE = 3
FREEZE_DURATION = 4
TELEPORT_RANGE = 9
DIG_RANGE = 10
 
# experience and level-ups
LEVEL_UP_BASE = 200
LEVEL_UP_FACTOR = 150
 
 
FOV_ALGO = 0  # default FOV algorithm
FOV_LIGHT_WALLS = True  # light walls or not
TORCH_RADIUS = 10
 
LIMIT_FPS = 20  # 20 frames-per-second maximum
 
